baseurl = "http://jsspen.github.io"
title = "Jordan Spencer | Dev"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "Jordan Spencer"
  info = "Full Stack Software Developer"
  description = "Jordan Spencer's Personal Website'"
  keywords = "blog,developer,personal,portfolio"
  avatarurl = "/images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2024

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/jsspen/"
[[params.social]]
  name = "Dev.to"
  icon = "fa-brands fa-dev fa-2x"
  weight = 2
  url = "https://dev.to/jsspen"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/jordanspencercbus/"
[[params.social]]
  name = "Email"
  icon = "fa-solid fa-envelope fa-2x"
  weight = 4
  url = "mailto:Jordan.S.Spencer@gmail.com"

# Menu links
#[[menu.main]]
  #name = "Blog"
  #weight = 1
  #url  = "posts/"
#[[menu.main]]
  #name = "About"
  #weight = 2
  #url = "about/"
